//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package nas

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// CPFSModifyFileSystem invokes the nas.CPFSModifyFileSystem API synchronously
// api document: https://help.aliyun.com/api/nas/cpfsmodifyfilesystem.html
func (client *Client) CPFSModifyFileSystem(request *CPFSModifyFileSystemRequest) (response *CPFSModifyFileSystemResponse, err error) {
	response = CreateCPFSModifyFileSystemResponse()
	err = client.DoAction(request, response)
	return
}

// CPFSModifyFileSystemWithChan invokes the nas.CPFSModifyFileSystem API asynchronously
// api document: https://help.aliyun.com/api/nas/cpfsmodifyfilesystem.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) CPFSModifyFileSystemWithChan(request *CPFSModifyFileSystemRequest) (<-chan *CPFSModifyFileSystemResponse, <-chan error) {
	responseChan := make(chan *CPFSModifyFileSystemResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.CPFSModifyFileSystem(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// CPFSModifyFileSystemWithCallback invokes the nas.CPFSModifyFileSystem API asynchronously
// api document: https://help.aliyun.com/api/nas/cpfsmodifyfilesystem.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) CPFSModifyFileSystemWithCallback(request *CPFSModifyFileSystemRequest, callback func(response *CPFSModifyFileSystemResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *CPFSModifyFileSystemResponse
		var err error
		defer close(result)
		response, err = client.CPFSModifyFileSystem(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// CPFSModifyFileSystemRequest is the request struct for api CPFSModifyFileSystem
type CPFSModifyFileSystemRequest struct {
	*requests.RpcRequest
	FsId      string           `position:"Query" name:"FsId"`
	FsDesc    string           `position:"Query" name:"FsDesc"`
	Bandwidth requests.Integer `position:"Query" name:"Bandwidth"`
	Capacity  requests.Integer `position:"Query" name:"Capacity"`
}

// CPFSModifyFileSystemResponse is the response struct for api CPFSModifyFileSystem
type CPFSModifyFileSystemResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateCPFSModifyFileSystemRequest creates a request to invoke CPFSModifyFileSystem API
func CreateCPFSModifyFileSystemRequest() (request *CPFSModifyFileSystemRequest) {
	request = &CPFSModifyFileSystemRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("NAS", "2017-06-26", "CPFSModifyFileSystem", "nas", "openAPI")
	return
}

// CreateCPFSModifyFileSystemResponse creates a response to parse from CPFSModifyFileSystem response
func CreateCPFSModifyFileSystemResponse() (response *CPFSModifyFileSystemResponse) {
	response = &CPFSModifyFileSystemResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
