//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package nas

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// CPFSDeleteFileSystem invokes the nas.CPFSDeleteFileSystem API synchronously
// api document: https://help.aliyun.com/api/nas/cpfsdeletefilesystem.html
func (client *Client) CPFSDeleteFileSystem(request *CPFSDeleteFileSystemRequest) (response *CPFSDeleteFileSystemResponse, err error) {
	response = CreateCPFSDeleteFileSystemResponse()
	err = client.DoAction(request, response)
	return
}

// CPFSDeleteFileSystemWithChan invokes the nas.CPFSDeleteFileSystem API asynchronously
// api document: https://help.aliyun.com/api/nas/cpfsdeletefilesystem.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) CPFSDeleteFileSystemWithChan(request *CPFSDeleteFileSystemRequest) (<-chan *CPFSDeleteFileSystemResponse, <-chan error) {
	responseChan := make(chan *CPFSDeleteFileSystemResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.CPFSDeleteFileSystem(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// CPFSDeleteFileSystemWithCallback invokes the nas.CPFSDeleteFileSystem API asynchronously
// api document: https://help.aliyun.com/api/nas/cpfsdeletefilesystem.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) CPFSDeleteFileSystemWithCallback(request *CPFSDeleteFileSystemRequest, callback func(response *CPFSDeleteFileSystemResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *CPFSDeleteFileSystemResponse
		var err error
		defer close(result)
		response, err = client.CPFSDeleteFileSystem(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// CPFSDeleteFileSystemRequest is the request struct for api CPFSDeleteFileSystem
type CPFSDeleteFileSystemRequest struct {
	*requests.RpcRequest
	FsId string `position:"Query" name:"FsId"`
}

// CPFSDeleteFileSystemResponse is the response struct for api CPFSDeleteFileSystem
type CPFSDeleteFileSystemResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateCPFSDeleteFileSystemRequest creates a request to invoke CPFSDeleteFileSystem API
func CreateCPFSDeleteFileSystemRequest() (request *CPFSDeleteFileSystemRequest) {
	request = &CPFSDeleteFileSystemRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("NAS", "2017-06-26", "CPFSDeleteFileSystem", "nas", "openAPI")
	return
}

// CreateCPFSDeleteFileSystemResponse creates a response to parse from CPFSDeleteFileSystem response
func CreateCPFSDeleteFileSystemResponse() (response *CPFSDeleteFileSystemResponse) {
	response = &CPFSDeleteFileSystemResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
